<img src="LOGO ITQ (2).png" width="200">

# **Ejercicio 2. Estandarización**
### **Nombre:** Mónica Guano
#### **Fecha:** 06/05/2026

In [40]:
from sklearn import preprocessing
import numpy as np

In [41]:
# Carga de datos.
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [42]:
# Limpieza de datos: estandarización.
standardizer = preprocessing.StandardScaler()

# Estandarizamos los datos de entrenamiento
X_train_std=standardizer.fit_transform(X_train)
print(X_train_std)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [43]:
X_train_2 = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [44]:
# Aplicamos los métodos "fit" y "transform" por separado
f=preprocessing.StandardScaler()
f=f.fit(X_train_2)
X_train_2_std = f.transform(X_train_2)
print(X_train_2_std)


[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


#### Comprobar si las matrices estandarizadas son iguales

In [51]:
# Comprobación de igualdad absoluta
son_exactamente_iguales = np.array_equal(X_train_std, X_train_2_std)

# Comprobación considerando pequeñas variaciones decimales (Recomendado)
son_similares = np.allclose(X_train_std, X_train_2_std)

print(f"¿Son exactamente iguales?: {son_exactamente_iguales}")
print(f"¿Son iguales (tolerancia decimal)?: {son_similares}")

¿Son exactamente iguales?: True
¿Son iguales (tolerancia decimal)?: True


In [50]:
# Una forma visual de comprobarlo:
# Si restas las dos matrices y el resultado es una matriz llena de ceros, son iguales:

print(X_train_std - X_train_2_std)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[**Enlace Tarea Clase 3:** Estandarización](http://localhost:8891/lab/tree/Pr%C3%A1ctica_Fundam.ML/Programa2.Estandarizacion.ipynb)

[**Link Github:** Estandarización](https://github.com/moniloag-png/Fundamentos_ML/blob/main/Programa2.Estandarizacion.ipynb)